feat: allow cors on proxy
ory/x pull request #489
Opened 2022-04-14 15:18 UTC by Benehiko

Add option to add CORS options to the proxy. This will allow the proxy to add the proper cors headers to requests that require them.

## Related Issue or Design Document

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added necessary documentation within the code base (if
      appropriate).

## Further comments

2022-04-14 21:00 UTC, Benehiko commented
Tests added :)

2022-04-14 21:32 UTC, aeneasr requested changes
Just two smal details :)

2022-04-14 21:32 UTC, aeneasr commented on proxy/proxy.go
> +			panic("could not get value from context")
Should we really panic here, or rather call `o.onReqError(r, err)`?

2022-04-14 21:32 UTC, aeneasr commented on proxy/proxy.go
> +			c = oh.(*HostConfig)
This could panic!

2022-04-19 13:44 UTC, aeneasr approved these changes

2022-04-19 14:53 UTC, zepatrik approved these changes

2022-04-19 14:54 UTC, merged