Automatic TLS certificate reload
ory/x pull request #507
Opened 2022-05-16 07:14 UTC by alnr

```
Adds the ability to automatically reload TLS certificates read from the filesystem in the background with a configurable interval.
```

## Related Issue or Design Document

Implements (part of) https://github.com/ory/hydra/issues/2850

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature: _this is an initial swing at the problem: let me know if you think the design is wrong._
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x] I have added tests that prove my fix is effective or that my feature
      works.
- [x] I have added necessary documentation within the code base (if
      appropriate).

## Further comments

The obvious alternative to periodically reloading every _x_ seconds is to use a file watching API, say https://github.com/fsnotify/fsnotify. The problem with that (beside introducing a new dependency) is that this functionality doesn't work with networked filesystems, e.g. Kubernetes secrets mounted into a pod. Since that's one of the most likely uses of the feature, fsnotify et al. are no good.

There's no mechanism to cancel the background polling. I thought about adding that but YAGNI prevailed here. Could be added later if somebody actually needs it.

2022-05-16 07:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ory/x?pullRequest=507) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ory/x?pullRequest=507) before we can accept your contribution.<br/><hr/>**Arne Luenser** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ory/x?pullRequest=507) it.</sub>

2022-05-17 15:37 UTC, alnr commented on tlsx/cert.go
> +			case errs <- err:
Sending to a nil channel blocks forever: https://go.dev/play/p/b3hKwHBubjB

2022-05-17 15:44 UTC, alnr commented on tlsx/cert.go
> +		for {
Yeah, I mentioned it's leaking in the PR description, but does it matter? The use case for this functionality is for long-running servers where this function is called once in `func main`. When that server shuts down, the whole program will almost certainly also quit shortly after.

An alternative could be a finalizer like so: https://github.com/ory/x/pull/502/files#diff-c4a0066906454afe9c02e0cf746cf1ea0263947b599072156c6f7e8691dce43dR45

Let me know what you think. Can easily add a context parameter too, of course.

2022-05-17 15:46 UTC, alnr commented on tlsx/cert.go
> +		return cert, nil
Fair enough. `cert` will never be `nil`, though.

2022-05-17 15:47 UTC, alnr commented on tlsx/cert.go
> +			case <-time.After(reloadInterval):
Yes, I learned that in the discussion for #502 which is a different take at this feature.

2022-05-24 09:51 UTC, aeneasr commented on tlsx/cert.go
> +		for {
> Yeah, I mentioned it's leaking in the PR description, but does it matter? The use case for this functionality is for long-running servers where this function is called once in func main. When that server shuts down, the whole program will almost certainly also quit shortly after.

Sorry, I missed this in the description! Leaky Go routines can be a mess when it comes to testing and flaky failures. We've spent time designing systems to handle everything gracefully. http://github.com/ory/graceful for example helps you discover when a process is being asked to exit, which we can use here to kill the goroutine.

IMO we don't need `runtime`. Adding a `select` with `<- ctx.Done()` is enough to close everything gracefully IMO.

2022-05-24 10:03 UTC, aeneasr commented
> Should we proceed with this PR or #502?

Unfortunately I did not see that we had #502 already :/ Looks like someone picked it up from the community :) I think #502 is going in the right direction, but there's still a couple of things we need to improve. Since it's using the `watcherx` package I think we're on a better path with #502 . Maybe you could help the author of #502 to address the remaining questions? :) Let me know what you think

2022-09-20 13:59 UTC, alnr commented
Seems like #502 went stale, so I updated this PR. @zepatrik can you take a look?

2022-09-21 11:03 UTC, zepatrik requested changes
Nice, this looks very solid, especially the test :+1: 
Just found some minor things to improve it further :wink:

2022-09-21 11:03 UTC, zepatrik commented on tlsx/cert_test.go
> +		t.Log("Got expected error:", err)
Can we add an assertion on this err?

2022-09-21 13:53 UTC, alnr commented on tlsx/cert.go
> +func PublicKey(key crypto.PrivateKey) interface{ Equal(x crypto.PublicKey) bool } {
This change kinda slipped in even though it's not related to the feature in this PR. Rationale is [here](https://pkg.go.dev/crypto#PublicKey):
```
type PublicKey [any](https://pkg.go.dev/builtin#any)
PublicKey represents a public key using an unspecified algorithm.

Although this type is an empty interface for backwards compatibility reasons, all public key types in the standard library implement the following interface

interface{
    Equal(x crypto.PublicKey) bool
}
```

2022-09-21 15:11 UTC, alnr commented on tlsx/cert.go
> +			case <-events:
done

2022-09-21 15:11 UTC, alnr commented on tlsx/cert_test.go
> +	case err := <-errs:
done

2022-09-21 15:11 UTC, alnr commented on tlsx/cert_test.go
> +		t.Log("Got expected error:", err)
done

2022-09-22 09:17 UTC, zepatrik approved these changes
Very nice :tada:

2022-09-22 09:18 UTC, merged